branches:
  only:
    - master

language: python

python:
  - "2.7"

env:
  - DJANGO_SETTINGS_MODULE='mapstory.settings.test_settings'

virtualenv:
  system_site_packages: true

services:
  - elasticsearch
  - postgresql

# GEONODE

sudo: required

dist: trusty

cache:
  directories:
    - gs
    - $HOME/.cache/pip
    - importer-test-files # REMOVE?

addons:
  postgresql: "9.3"

matrix:
  include:
    - python: "2.7"
      env: GS_VERSION=2.7.x GDAL_DATA="/usr/local/lib/gdal/share/gdal/"
    - python: "2.7"
      env: GS_VERSION=2.8.x GDAL_DATA="/usr/local/lib/gdal/share/gdal/"
    - python: "2.7"
      env: GS_VERSION=master GDAL_DATA="/usr/local/lib/gdal/share/gdal/"


before_install:
  - chmod +x ./scripts/geonode_install.sh
  - chmod +x ./scripts/geonode_before.sh
# END GEONODE


install:
  # INSTALL GEONODE
  - ./scripts/geonode_install.sh

  # INSTALL MAPSTORY
  - cd ..
  - git clone https://github.com/MapStory/geonode.git
  - cd mapstory
  - sudo apt-get -qq -y update
  - sudo apt-get install -y libgdal1h python-gdal
  - sudo apt-get install -y python-virtualenv python-imaging python-lxml python-pyproj python-shapely python-nose python-httplib2 python-httplib2 gettext
  - sudo add-apt-repository -y ppa:webupd8team/java
  - sudo apt-get update
  - sudo apt-get install -y --force-yes oracle-java8-installer ant maven2 libjai-imageio-core-java --no-install-recommends
  - sudo update-java-alternatives --set java-8-oracle
  - pip install -r requirements.txt
  - pip install urllib3[secure] --upgrade
  - pip install coveralls

before_script:
  # GEONODE
  - sudo scripts/geonode_before.sh
  # MAPSTORY
  - python manage.py migrate maps --noinput
  - python manage.py migrate layers --noinput
  - python manage.py migrate groups --noinput
  - sudo mkdir -p /var/lib/mapstory/media/
  - sudo chmod 775 /var/lib/mapstory/media/
  - sudo chown $USER /var/lib/mapstory/media/

script:
#  - flake8 osgeo_importer
  - coverage run ./manage.py test
  - coverage report
  - coverage html -d cover

after_success:
  - coveralls

notifications:
  slack: mapstory:E2W57xKNNOKDDqRmtQHNUlBK
