# Dev configuration
version: '3.1'
services:
  selenium:
    image: selenium/standalone-chrome
    links:
      - nginx
    networks:
      internal:
    expose:
      - "4444"

  protractor:
    build:
      context: .
      dockerfile: Dockerfile.protractor
    image: mapstory/protractor:master
    links:
      - selenium
      - nginx
    command: /bin/true
    volumes:
      - ./mapstory/tests/errors:/opt/mapstory/tests/e2e/errors
    networks:
      internal:

  postgres:
    image: mdillon/postgis:9.5
    env_file:
      - docker/env/dev/db_auth.env
      - docker/env/dev/postgres.env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      internal:
    expose:
      - "5432"

  pgadmin:
    image: mapstory/pgadmin:master
    command: --init-db
    links:
      - postgres
    env_file:
      - docker/env/dev/db_auth.env

  elasticsearch:
    ports:
      - "9200:9200"

  rabbitmq:
    image: mapstory/rabbitmq:master
    environment:
      - RABBITMQ_DEFAULT_USER=mapstory
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_DEFAULT_VHOST=mapstory

  django:
    image: mapstory/django:master
    links:
      - postgres
    env_file:
      - docker/env/dev/public_host.env
      - docker/env/dev/geoserver.env
      - docker/env/dev/mapstory.env
      - docker/env/dev/db_auth.env
    command: --init-db --test
    volumes:
      - ./cover:/srv/mapstory/cover
      - ./.git:/srv/mapstory/.git

  celery:
    image: mapstory/django:master
    links:
      - postgres
    env_file:
      - docker/env/dev/public_host.env
      - docker/env/dev/geoserver.env
      - docker/env/dev/mapstory.env
      - docker/env/dev/db_auth.env
    environment:
      CELERY_NUM_WORKERS: 1

  geoserver:
    image: mapstory/geoserver-2.11:master
    links:
      - postgres
    env_file:
      - docker/env/dev/public_host.env
      - docker/env/dev/geoserver.env
      - docker/env/dev/db_auth.env

  nginx:
    image: mapstory/nginx:master
    env_file:
      - docker/env/dev/public_host.env
    networks:
      internal:
        aliases:
          - docker

volumes:
  postgres:
